fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: '5.2.0'
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: 'v6.4.0'
  symlinks:
    nsd: "#{source_dir}"
